import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import Authprovider from './component/Authprovider'
import { Toaster } from './component/ui/toaster'
import NewNavbar from './component/layout/NewNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark bg-background antialiased no-scrollbar scroll-smooth'>
      <body className={inter.className}>
    <Authprovider>
      {/* <Header /> */}
      {/* <main className="max-w-7xl mx-auto p-4"> */}
<div className=''>

      {children}
</div>
     
      {/* </main> */}
      <Toaster/>
      </Authprovider>
      
      </body>
    </html>
  )
}
